### ISSUE TITLE
failed on clone and compile easy_pbr

### ISSUE THREAD

**Issue by ark1234** [AIS-Bonn/lattice_net#3]
Firstly, I want to think you so much for your good work!

Sorry to interrupt you from your busy time.

I met some problems on clone easy_pbr
`Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:aantron/better-enums.git' into submodule path '/workspace/easy_pbr/deps/better_enums' failed`

And I tried to clone the deps by myself, it still didn't work.

I am not familiar with GitHub, if possible, could you push your compiled image into the docker hub?

**Comment by ark1234** [comment]
I tried to figure out the aforementioned problem, but when I run the script, it said:
`RuntimeError: NVRTC error: NVRTC_ERROR_INVALID_OPTION`

I use GeForce RTX 2080 Ti

Seems should support your environment.

Sorry again for interrupt you from your busy time

**Comment by RaduAlexandru** [comment]
Thank you for letting me know of the issue. 
I made a small change to easy_pbr now. Can you try to clone it again?
`git clone --recursive https://github.com/RaduAlexandru/easy_pbr`

As for the NVRTC error, what script raised such error?
First, please make sure you have installed the Nvidia drivers on your host machine. Running "nvidia-smi" in a terminal should tell you which Driver Version you have or it will raise an error if they are not installed.

Please let me know if the error persists.

**Comment by ark1234** [comment]
Thank you so much for your quick response.

As I said, I figured out the git clone problem I mentioned previously, and now I can successfully compile and run the code on Tesla A100 GPU. However, I don't have too much access time to that GPU since it is on a shared server of my university. So, I tried to use the compiled image on our lab's server, which only has some GeForce RTX 2080 Ti and Quadro RTX 6000, which only support CUDA Version of 11.0. I saw your new Dockerfile the CUDA version is 11.1.1. And when I run `python ln_train.py ` in the latticenet_py folder. It gave me:
`Compiler options: -std=c++11 --use_fast_math -arch=compute_-251149912 
Traceback (most recent call last):
  File "ln_train.py", line 212, in <module>
    main()  # This is what you would have, but the following is useful:
  File "ln_train.py", line 207, in main
    run()
  File "ln_train.py", line 94, in run
    lattice=Lattice.create(config_path, "lattice")
RuntimeError: NVRTC error: NVRTC_ERROR_INVALID_OPTION`

By the way, when I noticed the CUDA version problem, I tried to modify your Dockerfile several times, sometimes, I can generate images successfully even compile easy_pbr and data_loaders. But I never successfully compile lattice_net with the modified Dockerfile generated image.  
Moreover,  I tried to use your old version of Dockerfile, the version before you change to support RTX 3000 GPU, it cannot generate the image either, it stopped with this:
`Step 60/82 : RUN sudo apt-get update && sudo apt-get -y install python3-pip python3-tk python3-pyqt5 python3-crypto python3-gnupg python3-dbg && sh "./cleanup.sh"
 ---> Running in 85f55c656c43
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Ign:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  At least one invalid signature was encountered.
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Err:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  At least one invalid signature was encountered.
Err:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  At least one invalid signature was encountered.
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [696 B]
Get:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Err:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
  At least one invalid signature was encountered.
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Ign:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg
Ign:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg
Reading package lists...
W: GPG error: http://archive.ubuntu.com/ubuntu bionic InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-backports InRelease' is not signed.
W: GPG error: http://security.ubuntu.com/ubuntu bionic-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.ubuntu.com/ubuntu bionic-security InRelease' is not signed.
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release: At least one invalid signature was encountered.
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' is not signed.
W: GPG error: https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release: At least one invalid signature was encountered.
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' is not signed.
The command '/bin/sh -c sudo apt-get update && sudo apt-get -y install python3-pip python3-tk python3-pyqt5 python3-crypto python3-gnupg python3-dbg && sh "./cleanup.sh"' returned a non-zero code: 100
`
